source("http://bioconductor.org/biocLite.R")
biocLite("maftools")
library(maftools)
snvs_maf = read.maf(maf ='~/Desktop/somatic.snvs.maf')
plotmafSummary(maf = snvs_maf, rmOutlier = TRUE, addStat = 'median')
lollipopPlot(snvs_maf, gene="BRAF", AACol="HGVSp_Short", showMutationRate=TRUE)
rainfallPlot(maf= snvs_maf, detectChangePoints=TRUE, pointSize=0.6)
luad.mutload <- tcgaCompare(maf= snvs_maf)
plotVaf(maf= snvs_maf)
luad.pfam <- pfamDomains(maf= snvs_maf, AACol="HGVSp_Short", top=10)
vafclust <- inferHeterogeneity(maf= snvs_maf, tsb="TUMOR")
plotClusters(clusters=vafclust)